sudo: required
dist: bionic
language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mingw-w64

script:
  - make sslscan CC=clang
  - make sslscan CC=gcc
  - make static CC=clang
  - make static CC=gcc
  - make -f Makefile.mingw
